SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;


CREATE TABLE IF NOT EXISTS `capitals` (
  `id` int(10) unsigned NOT NULL,
  `country` varchar(45) CHARACTER SET utf8mb4 DEFAULT NULL,
  `capital` varchar(45) CHARACTER SET utf8mb4 DEFAULT NULL
) ENGINE=MyISAM AUTO_INCREMENT=235 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `capitals` (`id`, `country`, `capital`) VALUES
(1, 'United Arab Emirates', 'Abu Dhabi'),
(2, 'Nigeria', 'Abuja'),
(3, 'Ghana', 'Accra'),
(4, 'Pitcairn Islands', 'Adamstown'),
(5, 'Ethiopia', 'Addis Ababa'),
(6, 'Algeria', 'Algiers'),
(7, 'Niue', 'Alofi'),
(8, 'Jordan', 'Amman'),
(9, 'Netherlands', 'Amsterdam'),
(10, 'Andorra', 'Andorra la Vella'),
(11, 'Turkey', 'Ankara'),
(12, 'Madagascar', 'Antananarivo'),
(13, 'Samoa', 'Apia'),
(14, 'Turkmenistan', 'Ashgabat'),
(15, 'Eritrea', 'Asmara'),
(16, 'Kazakhstan', 'Astana'),
(17, 'Paraguay', 'Asuncion'),
(18, 'Greece', 'Athens'),
(19, 'Cook Islands', 'Avarua'),
(20, 'Iraq', 'Baghdad'),
(21, 'Azerbaijan', 'Baku'),
(22, 'Mali', 'Bamako'),
(23, 'Brunei', 'Bandar Seri Begawan'),
(24, 'Thailand', 'Bangkok'),
(25, 'Central African Republic', 'Bangui'),
(26, 'Gambia', 'Banjul'),
(27, 'Saint Kitts and Nevis', 'Basseterre'),
(28, 'China', 'Beijing'),
(29, 'Lebanon', 'Beirut'),
(30, 'Serbia', 'Belgrade'),
(31, 'Belize', 'Belmopan'),
(32, 'Germany', 'Berlin'),
(33, 'Switzerland', 'Bern'),
(34, 'Kyrgyzstan', 'Bishkek'),
(35, 'Guinea-Bissau', 'Bissau'),
(36, 'Colombia', 'Bogota'),
(37, 'Brazil', 'Brasilia'),
(38, 'Slovakia', 'Bratislava'),
(39, 'Republic of the Congo', 'Brazzaville'),
(40, 'Barbados', 'Bridgetown'),
(41, 'Belgium', 'Brussels'),
(42, 'Romania', 'Bucharest'),
(43, 'Hungary', 'Budapest'),
(44, 'Argentina', 'Buenos Aires'),
(45, 'Burundi', 'Bujumbura'),
(46, 'Egypt', 'Cairo'),
(47, 'Australia', 'Canberra'),
(48, 'Venezuela', 'Caracas'),
(49, 'Saint Lucia', 'Castries'),
(50, 'French Guiana', 'Cayenne'),
(51, 'United States Virgin Islands', 'Charlotte Amalie'),
(52, 'Moldova', 'Chisinau'),
(53, 'Turks and Caicos Islands', 'Cockburn Town'),
(54, 'Guinea', 'Conakry'),
(55, 'Denmark', 'Copenhagen'),
(56, 'Senegal', 'Dakar'),
(57, 'Syria', 'Damascus'),
(58, 'Bangladesh', 'Dhaka'),
(59, 'East Timor (Timor-Leste)', 'Dili'),
(60, 'Djibouti', 'Djibouti'),
(61, 'Tanzania', 'Dodoma'),
(62, 'Qatar', 'Doha'),
(63, 'Isle of Man', 'Douglas'),
(64, 'Ireland', 'Dublin'),
(65, 'Tajikistan', 'Dushanbe'),
(66, 'Tristan da Cunha', 'Edinburgh of the Seven Seas'),
(67, 'Sahrawi Arab Democratic Republic', 'El Aaiun'),
(68, 'Akrotiri and Dhekelia', 'Episkopi Cantonment'),
(69, 'Christmas Island', 'Flying Fish Cove'),
(70, 'Sierra Leone', 'Freetown'),
(71, 'Tuvalu', 'Funafuti'),
(72, 'Botswana', 'Gaborone'),
(73, 'Cayman Islands', 'George Town'),
(74, 'Gibraltar', 'Gibraltar'),
(75, 'South Georgia and the South Sandwich Islands', 'Grytviken'),
(76, 'Guatemala', 'Guatemala City'),
(77, 'Saint Barthelemy', 'Gustavia'),
(78, 'Guam', 'Hagatna'),
(79, 'Bermuda', 'Hamilton'),
(80, 'Easter Island', 'Hanga Roa'),
(81, 'Vietnam', 'Hanoi'),
(82, 'Zimbabwe', 'Harare'),
(83, 'Somaliland', 'Hargeisa'),
(84, 'Cuba', 'Havana'),
(85, 'Finland', 'Helsinki'),
(86, 'Solomon Islands', 'Honiara'),
(87, 'Pakistan', 'Islamabad'),
(88, 'Indonesia', 'Jakarta'),
(89, 'Saint Helena', 'Jamestown'),
(90, 'Israel', 'Jerusalem'),
(91, 'South Sudan', 'Juba'),
(92, 'Afghanistan', 'Kabul'),
(93, 'Uganda', 'Kampala'),
(94, 'Nepal', 'Kathmandu'),
(95, 'Sudan', 'Khartoum'),
(96, 'Ukraine', 'Kiev'),
(97, 'Rwanda', 'Kigali'),
(98, 'Jamaica', 'Kingston'),
(99, 'Saint Vincent and the Grenadines', 'Kingstown'),
(100, 'Democratic Republic of the Congo', 'Kinshasa'),
(101, 'Malaysia', 'Kuala Lumpur'),
(102, 'Kuwait', 'Kuwait City'),
(103, 'Gabon', 'Libreville'),
(104, 'Malawi', 'Lilongwe'),
(105, 'Peru', 'Lima'),
(106, 'Portugal', 'Lisbon'),
(107, 'Slovenia', 'Ljubljana'),
(108, 'Togo', 'Lom'),
(109, 'United Kingdom', 'London'),
(110, 'Angola', 'Luanda'),
(111, 'Zambia', 'Lusaka'),
(112, 'Luxembourg', 'Luxembourg'),
(113, 'Spain', 'Madrid'),
(114, 'Marshall Islands', 'Majuro'),
(115, 'Equatorial Guinea', 'Malabo'),
(116, 'Maldives', 'Mal'),
(117, 'Nicaragua', 'Managua'),
(118, 'Bahrain', 'Manama'),
(119, 'Philippines', 'Manila'),
(120, 'Mozambique', 'Maputo'),
(121, 'Saint Martin', 'Marigot'),
(122, 'Lesotho', 'Maseru'),
(123, 'Wallis and Futuna', 'Mata-Utu'),
(124, 'Swaziland', 'Mbabane'),
(125, 'Palau', 'Melekeok'),
(126, 'Mexico', 'Mexico City'),
(127, 'Belarus', 'Minsk'),
(128, 'Somalia', 'Mogadishu'),
(129, 'Monaco', 'Monaco'),
(130, 'Liberia', 'Monrovia'),
(131, 'Uruguay', 'Montevideo'),
(132, 'Comoros', 'Moroni'),
(133, 'Russia', 'Moscow'),
(134, 'Oman', 'Muscat'),
(135, 'Kenya', 'Nairobi'),
(136, 'Bahamas', 'Nassau'),
(137, 'Burma', 'Naypyidaw'),
(138, 'India', 'New Delhi'),
(139, 'Niger', 'Niamey'),
(140, 'Cyprus', 'Nicosia'),
(141, 'Mauritania', 'Nouakchott'),
(142, 'New Caledonia', 'Noum'),
(143, 'Greenland', 'Nuuk'),
(144, 'Aruba', 'Oranjestad'),
(145, 'Norway', 'Oslo'),
(146, 'Canada', 'Ottawa'),
(147, 'Burkina Faso', 'Ouagadougou'),
(148, 'American Samoa', 'Pago Pago'),
(149, 'Federated States of Micronesia', 'Palikir'),
(150, 'Panama', 'Panama City'),
(151, 'French Polynesia', 'Papeete'),
(152, 'Suriname', 'Paramaribo'),
(153, 'France', 'Paris'),
(154, 'Sint Maarten', 'Philipsburg'),
(155, 'Cambodia', 'Phnom Penh'),
(156, 'Montserrat', 'Plymouth'),
(157, 'Montenegro', 'Podgorica'),
(158, 'Mauritius', 'Port Louis'),
(159, 'Papua New Guinea', 'Port Moresby'),
(160, 'Vanuatu', 'Port Vila'),
(161, 'Haiti', 'Port-au-Prince'),
(162, 'Trinidad and Tobago', 'Port of Spain'),
(163, 'Benin', 'Porto-Novo'),
(164, 'Czech Republic', 'Prague'),
(165, 'Cape Verde', 'Praia'),
(166, 'South Africa', 'Pretoria'),
(167, 'Kosovo', 'Pristina'),
(168, 'North Korea', 'Pyongyang'),
(169, 'Ecuador', 'Quito'),
(170, 'Morocco', 'Rabat'),
(171, 'Iceland', 'Reykjav'),
(172, 'Latvia', 'Riga'),
(173, 'Saudi Arabia', 'Riyadh'),
(174, 'British Virgin Islands', 'Road Town'),
(175, 'Italy', 'Rome'),
(176, 'Dominica', 'Roseau'),
(177, 'Northern Mariana Islands', 'Saipan'),
(178, 'Costa Rica', 'San Jos'),
(179, 'Puerto Rico', 'San Juan'),
(180, 'San Marino', 'San Marino'),
(181, 'El Salvador', 'San Salvador'),
(182, 'Chile', 'Santiago'),
(183, 'Dominican Republic', 'Santo Domingo'),
(184, 'Sao Tome and Principe', 'Sao Tome'),
(185, 'Bosnia and Herzegovina', 'Sarajevo'),
(186, 'South Korea', 'Seoul'),
(187, 'Singapore', 'Singapore'),
(188, 'Macedonia', 'Skopje'),
(189, 'Bulgaria', 'Sofia'),
(190, 'Sri Lanka', 'Sri Jayawardenepura Kotte'),
(191, 'Jersey', 'St. Helier'),
(192, 'Guernsey', 'St. Peter Port'),
(193, 'Saint Pierre and Miquelon', 'St. Pierre'),
(194, 'Falkland Islands', 'Stanley'),
(195, 'Nagorno-Karabakh Republic', 'Stepanakert'),
(196, 'Sweden', 'Stockholm'),
(197, 'Bolivia', 'Sucre'),
(198, 'Abkhazia', 'Sukhumi'),
(199, 'Fiji', 'Suva'),
(200, 'Taiwan', 'Taipei'),
(201, 'Estonia', 'Tallinn'),
(202, 'Kiribati', 'Tarawa'),
(203, 'Uzbekistan', 'Tashkent'),
(204, 'Georgia', 'Tbilisi'),
(205, 'Honduras', 'Tegucigalpa'),
(206, 'Iran', 'Tehran'),
(207, 'Bhutan', 'Thimphu'),
(208, 'Albania', 'Tirana'),
(209, 'Transnistria', 'Tiraspol'),
(210, 'Japan', 'Tokyo'),
(211, 'Faroe Islands', 'Torshavn'),
(212, 'Libya', 'Tripoli'),
(213, 'South Ossetia', 'Tskhinvali'),
(214, 'Tunisia', 'Tunis'),
(215, 'Mongolia', 'Ulan Bator'),
(216, 'Liechtenstein', 'Vaduz'),
(217, 'Malta', 'Valletta'),
(218, 'Anguilla', 'The Valley'),
(219, 'Vatican City', 'Vatican City'),
(220, 'Seychelles', 'Victoria'),
(221, 'Austria', 'Vienna'),
(222, 'Laos', 'Vientiane'),
(223, 'Lithuania', 'Vilnius'),
(224, 'Poland', 'Warsaw'),
(225, 'United States', 'Washington, D.C.'),
(226, 'New Zealand', 'Wellington'),
(227, 'Cocos (Keeling) Islands', 'West Island'),
(228, 'Curacao', 'Willemstad'),
(229, 'Namibia', 'Windhoek'),
(230, 'Ivory Coast', 'Yamoussoukro'),
(231, 'Cameroon', 'Yaound'),
(232, 'Nauru', 'Yaren'),
(233, 'Armenia', 'Yerevan'),
(234, 'Croatia', 'Zagreb');


ALTER TABLE `capitals`
  ADD PRIMARY KEY (`id`);


ALTER TABLE `capitals`
  MODIFY `id` int(10) unsigned NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=235;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
